import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/config";
import SessionProvider from "./components/sessionprovider/sessionauth";
import { getSession } from "next-auth/react"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "A.M Turing",
  description: "Generated by A.M Turing",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  const session = await getServerSession(authOptions);
  
  return (
    <html lang="en" className="h-full dark">
      <body className={inter.className}>
        <SessionProvider >
          {children}
       </SessionProvider>
      </body>
    </html>
  );
}
